x = 10

def my_function():
    x = x + 5
    print(x)

my_function() # x has no value inside the def block, this will throw and error